services:
  grl-api:
    image: grl-api:<IMAGE_TAG>
    container_name: grl-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5001:5001"
    restart: unless-stopped
    networks:
      - grl-backend
    depends_on:
      - grl-db

  grl-db:
    image: postgres:15-alpine
    container_name: grl-db
    environment:
      - POSTGRES_DB=<DB_NAME>
      - POSTGRES_USER=<DB_USER>
      - POSTGRES_PASSWORD=<DB_PASSWORD>
    volumes:
      - grl_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - grl-backend

networks:
  grl-backend:
    external: true

volumes:
  grl_db_data:
    driver: local
